In [2]:
import numpy as np
a=np.array([4,5,6])
a

array([4, 5, 6])

In [6]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [7]:
a.sum()

15

In [8]:
b.sum()

21.5

In [10]:
a.min()

4

In [11]:
b.min()

1.5

In [14]:
b.max(axis=1)

array([3., 6.])

In [13]:
b.max()

6.0

In [16]:
a.cumsum(axis=0)


array([ 4,  9, 15], dtype=int32)

In [17]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [18]:
b.cumsum(axis=0)

array([[1.5, 2. , 3. ],
       [5.5, 7. , 9. ]])

In [19]:
a.mean()


5.0

In [20]:
b.mean()

3.5833333333333335

In [21]:
np.median(a)

5.0

In [22]:
np.median(b)

3.5

In [23]:
np.std(b)

1.5920810978785667

In [24]:
np.std(a)

0.816496580927726

In [40]:
a=np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [48]:
b=np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [49]:
a+b

array([ 5,  7,  9, 11, 13])

In [52]:
a=np.array([
    [0,0,0],
    [1,1,1],
    [2,2,2],
    [3,3,3]
])
a

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [53]:
 a.shape

(4, 3)

In [54]:
b=np.array([[6,7,8]])
b

array([[6, 7, 8]])

In [55]:
b.shape

(1, 3)

In [56]:
a+b

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11]])

In [60]:
a=np.arange(0,8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [61]:
a+10

array([10, 11, 12, 13, 14, 15, 16, 17])

In [82]:
a-10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3])

In [63]:
a*10

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [64]:
a%10

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [65]:
a-5

array([-5, -4, -3, -2, -1,  0,  1,  2])

In [74]:
a=np.arange(0,8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [76]:
a>2

array([False, False, False,  True,  True,  True,  True,  True])

In [79]:
a>3

array([False, False, False, False,  True,  True,  True,  True])

In [80]:
a<5

array([ True,  True,  True,  True,  True, False, False, False])

In [81]:
a==6

array([False, False, False, False, False, False,  True, False])

In [84]:
x=lambda x:x**2
x(9)

81

In [93]:
y=lambda x:x**2
x(4)

16

In [96]:
a=lambda x,y:x+y
a(10,2)

12

In [105]:
b= lambda x:x[4]=='a'
b('apple')                                                                                         


False

In [103]:
b('grapes')

False

In [106]:
l=[1,2,3,4,5,6,7]
l

[1, 2, 3, 4, 5, 6, 7]

In [107]:
list(map(lambda x:x*2,l))

[2, 4, 6, 8, 10, 12, 14]

In [108]:
list(map(lambda x:x%2==0,l))

[False, True, False, True, False, True, False]

In [3]:
student=[{'name':'sneha',
         'fathername':'sunil',},
        {'name':'priya',
        'fathername':'suma'}]
student


[{'name': 'sneha', 'fathername': 'sunil'},
 {'name': 'priya', 'fathername': 'suma'}]

In [118]:
list(map(lambda student:student['fathername'],student))

['sunil', 'suma']

In [121]:
l=[1,2,4,5,6,8,7]
list(filter(lambda x:x>6,l))

[8, 7]

In [130]:
vegetables=('onion','potato','drumstick','tomato')

In [134]:
list(filter(lambda vegetable:'p'in vegetable,vegetables))

['potato']

In [135]:
functools.reduce(lambda x,y:x if x>y else y, l1)

56

In [122]:
import functools
l1 =[12,34,56,21]
l1

[12, 34, 56, 21]